let modelsJson = [ //Esse aqui serve para colocar a informação na pagina, daqui eu pego para colocar em outros scripts //
    {id:1, name:'KIT 3 MOLETONS TOPPER CLASSIC MASCULINO', img:'img/356838-1.webp', price:[130.00, 150.00, 200.00], sizes:['P', 'M', 'G'], description:'Garanta total conforto sem perder o estilo em dias mais frios junto ao Kit 3 Moletons Topper Classic.'},
    {id:2, name:'KIT 2 CAMISETAS TOPPER FUTEBOL TECHNIC MASCULINO', img:'img/356814-1.webp', price:[100.00, 150.00, 200.00], sizes:['P', 'M', 'G'], description:'Garanta maior performance em seus trinos e jogos junto ao Kit 2Camisetas Topper Technic.'},
    {id:3, name:'Ki 61 - Hien', img:'img/Ki61Hien.png', price:[100.00, 150.00, 200.00], sizes:['P', 'M', 'G'], description:'Caça fabricado pela Kawasaki para o exercito japones, com motor em linha'},
    {id:4, name:'Me 109 G6', img:'img/Me109G6.png', price:[100.00, 150.00, 200.00], sizes:['P', 'M', 'G'], description:'Famoso caça da Messerchmnitt, voado pelos maiores ases da Luftwaffe, a versão G foi a mais produzida'},
    {id:5, name:'P47 D - Thunderbolt', img:'img/P47D.png', price:[100.00, 150.00, 200.00], sizes:['P', 'M', 'G'], description:'Caça bombardeiro de fabricação americana utilizado pela FAB'},
    {id:6, name:'P51 D - Mustang', img:'img/P51D.png', price:[100.00, 150.00, 200.00], sizes:['P', 'M', 'G'], description:'O mais conhecido caça americano, importante escolta para os bombardeiros diurnos'},
    {id:7, name:'Spitfire Mk-IX', img:'img/SpitMk9.png', price:[100.00, 150.00, 200.00], sizes:['P', 'M', 'G'], description:'O mais famosa caça britânico, utilizado em toda a guerra'},
    {id:8, name:'A6M Zero', img:'img/Zero.png', price:[100.00, 150.00, 200.00], sizes:['P', 'M', 'G'], description:'O mais famoso caça da marinha japonesa, terror do pacífico nos anos iníciais da guerra'}
];