let modelsJson = [ //Esse aqui serve para colocar a informação na pagina, daqui eu pego para colocar em outros scripts //
    {id:1, name:'KIT 3 MOLETONS TOPPER CLASSIC MASCULINO', img:'img/356838-1.webp', price:[130.00, 180.00, 200.00], sizes:['P', 'M', 'G'], description:'Garanta total conforto sem perder o estilo em dias mais frios junto ao Kit 3 Moletons Topper Classic.'},
    {id:2, name:'KIT 2 CAMISETAS TOPPER FUTEBOL TECHNIC MASCULINO', img:'img/356814-1.webp', price:[150.00, 200.00, 300.00], sizes:['P', 'M', 'G'], description:'Garanta maior performance em seus trinos e jogos junto ao Kit 2Camisetas Topper Technic.'},
    {id:3, name:'CAMISETA DE FUTEBOL INFANTIL F100', img:'img/camiseta-de-futebola-f100-infantil1.webp', price:[50.00, 60.00, 80.00], sizes:['P', 'M', 'G'], description:'Nossa equipe desenvolveu a camiseta F100, com leveza e respirabilidade.'},
    {id:4, name:'REGATA TOPPER TREINO SUBLIME MASCULINA', img:'img/356696-1.webp', price:[45.00, 46.00, 55.00], sizes:['P', 'M', 'G'], description:'Aumente sua performance durante os treinos junto a Regata Topper Sublime.'},
    {id:5, name:'REGATA SELENE FITNESS FEMININA', img:'img/309664.webp', price:[45.00, 48.00, 55.00], sizes:['P', 'M', 'G'], description:'A Regata Selene Fitness Feminina é ótima para treinar em dias de temperatura mais alta'},
    {id:6, name:'KIT 2 CAMISAS POLO KAPPA DONATELLO MASCULINO', img:'img/350151-1.webp', price:[89.00, 95.00, 97.00], sizes:['P', 'M', 'G'], description:'O Kit 2 Camisas Polo Kappa Donatello Masculina é ideal para qualquer ocasião do dia a dia'},
    {id:7, name:'KIT 3 CALÇAS LEGGING SELENE SEM COSTURA FEMININA', img:'img/352472-1.webp', price:[300.00, 320.00, 350.00], sizes:['P', 'M', 'G'], description:'Dê um up nos treinos dentro ou fora da academia com a Calça Legging Selene Sem Costura Feminina.'},
    {id:8, name:'REGATA ESPORTE LEGAL RAJADA PLANK UV45 FEMININA', img:'img/272464.webp', price:[35.90, 39.00, 40.00], sizes:['P', 'M', 'G'], description:'A Regata Esporte Legal Rajada Plank Feminina é o que faltava para compor seu look do dia a dia ou de atividade física'},
    {id:9, name:'CAMISA REUSCH UNDERJERSEY M/C', img:'img/256221.webp', price:[29.90, 30.00, 35.00], sizes:['P', 'M', 'G'], description:'Malha em poliéster com elastano que se ajusta perfeitamente ao corpo.'},
    {id:10, name:'JAQUETA CORTA VENTO TOPPER PRINT II MASCULINA', img:'img/353265-1.webp', price:[150.00, 160.00, 180.00], sizes:['P', 'M', 'G'], description:'Com a Jaqueta Topper quebra Vento Print II Masculina, você se mantém protegido do vento frio com muito mais conforto'},
    {id:11, name:'CAMISA ESPORTE LEGAL PORUS POLIAMIDA', img:'img/288197-3.webp', price:[49.00, 50.00, 60.00], sizes:['P', 'M', 'G'], description:'A Camisa Esporte Legal Porus Poliamida é ideal para seu treino, caminhada ou corrida.'},
    {id:12, name:'CAMISA KANXA BABY LOOK CRISP FATOR PROTEÇÃO SOLAR', img:'img/255793.webp', price:[39.00, 40.00, 49.00], sizes:['P', 'M', 'G'], description:'A alta tecnologia do tecido Dry Soft Ice foi desenvolvida para permitir mais liberdade de movimentos'},
];